# Generated by Django 3.2.2 on 2021-05-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtor',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
