# Generated by Django 3.2.2 on 2021-05-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_produtor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtor',
            name='telefone',
        ),
        migrations.DeleteModel(
            name='Telefone',
        ),
    ]
