# Generated by Django 3.2.2 on 2021-12-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.familiaproduto'),
        ),
    ]
