# Generated by Django 3.2.2 on 2021-05-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mapadecampo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CestasFeitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('cestas_pequenas', models.PositiveIntegerField()),
                ('cestas_grandes', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='mapadecampo',
            name='urgente',
        ),
        migrations.AddField(
            model_name='produto',
            name='medida',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unidade'), (2, 'Kg')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_cesta_grande',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_cesta_pequena',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sazonalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.SmallIntegerField()),
                ('sazonalidade', models.FloatField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
    ]
