# Generated by Django 3.2.2 on 2021-05-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210527_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cestasfeitas',
            name='cestas_grandes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cestasfeitas',
            name='cestas_pequenas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapadecampo',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapadecampo',
            name='quantidade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_cesta_grande',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_cesta_pequena',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
