# Generated by Django 3.2.2 on 2021-06-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_produto_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtor',
            name='telefone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produtor',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Final'), (2, 'Potencial'), (3, 'Antigo'), (4, 'Lista Negra')]),
        ),
    ]
