# Generated by Django 3.2.2 on 2021-06-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210603_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='quantidade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
