# Generated by Django 3.2.2 on 2021-06-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_disponibilidade_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='medida',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unidade'), (2, 'Kg')], null=True),
        ),
    ]
