# Generated by Django 3.2.2 on 2021-06-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_ranking_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtor',
            name='estado',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Final'), (2, 'Potencial'), (3, 'Antigo'), (4, 'Lista Negra')], null=True),
        ),
    ]
