# Generated by Django 3.2.2 on 2021-06-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cestaresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidade',
            name='on_hold',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
