# Generated by Django 3.2.2 on 2021-06-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_disponibilidade_on_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='on_hold',
            field=models.BooleanField(default=True),
        ),
    ]
