# Generated by Django 3.2.2 on 2021-06-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_disponibilidade_on_hold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sazonalidade',
            old_name='semana',
            new_name='mes',
        ),
    ]
