# Generated by Django 3.2.2 on 2021-06-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_semana_sazonalidade_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sazonalidade',
            name='sazonalidade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
