# Generated by Django 3.2.2 on 2021-06-30 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_sazonalidade_sazonalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.familiaproduto'),
        ),
    ]
