# Generated by Django 3.2.2 on 2021-06-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_produto_familia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sazonalidade',
            old_name='sazonalidade',
            new_name='abril',
        ),
        migrations.AddField(
            model_name='sazonalidade',
            name='agosto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sazonalidade',
            name='dezembro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sazonalidade',
            name='fevereiro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sazonalidade',
            name='janeiro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sazonalidade',
            name='julho',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sazonalidade',
            name='junho',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sazonalidade',
            name='maio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sazonalidade',
            name='março',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sazonalidade',
            name='novembro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sazonalidade',
            name='outubro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sazonalidade',
            name='setembro',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
