# Generated by Django 3.2.2 on 2021-06-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210630_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sazonalidade',
            old_name='março',
            new_name='marco',
        ),
    ]
