# Generated by Django 3.2.2 on 2021-07-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_março_sazonalidade_marco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapadecampo',
            name='medida',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unidade'), (2, 'Kg')], null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Verde'), (2, 'Fruta'), (3, 'Legume'), (4, 'Outro')], null=True),
        ),
    ]
