# Generated by Django 3.2.2 on 2021-07-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210701_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sazonalidade',
            name='mes',
        ),
    ]
