# Generated by Django 3.2.2 on 2021-07-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_sazonalidade_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='noWorkLastWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
            ],
        ),
    ]
